(() => {
  const canvas = document.getElementById('gameCanvas');
  const ctx = canvas.getContext('2d');
  const wrap = document.getElementById('canvasWrap');
  const $ = id => document.getElementById(id);
  const state = { credits:240, hp:20, energy:3, wave:0, kills:0, xp:0, level:1, points:1, speed:1, paused:false, active:false, selected:'cannon', towers:[], enemies:[], shots:[], particles:[], skills:new Set(['core']), hover:null, time:0, spawnLeft:0, spawnTimer:0 };
  const types = { cannon:{cost:90, range:155, rate:1.05, damage:30, color:'#ffbf5f'}, rapid:{cost:65, range:132, rate:.32, damage:10, color:'#69dcff'}, support:{cost:120, range:120, rate:1.4, damage:7, color:'#c8ee6d'} };
  const path = [{x:0,y:2},{x:1,y:2},{x:2,y:2},{x:2,y:3},{x:3,y:3},{x:4,y:3},{x:4,y:4},{x:5,y:4},{x:6,y:4},{x:6,y:3},{x:7,y:3},{x:8,y:3},{x:8,y:2},{x:9,y:2}];
  const buildable = [{x:1,y:1},{x:2,y:1},{x:3,y:2},{x:3,y:4},{x:4,y:2},{x:5,y:3},{x:5,y:5},{x:6,y:2},{x:7,y:2},{x:7,y:4},{x:8,y:4}];
  let W=0,H=0,origin={x:0,y:0},tileW=88,tileH=44,dpr=1,last=performance.now();
  function resize(){dpr=Math.min(devicePixelRatio||1,2); W=wrap.clientWidth;H=wrap.clientHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);origin={x:W/2-4*tileW/2,y:Math.max(90,H/2-90)}}
  addEventListener('resize',resize);resize();
  const iso=(x,y)=>({x:origin.x+(x-y)*tileW/2,y:origin.y+(x+y)*tileH/2});
  function poly(points,fill,stroke){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
  function tile(x,y,road=false,build=false){const p=iso(x,y),top=[{x:p.x,y:p.y-tileH/2},{x:p.x+tileW/2,y:p.y},{x:p.x,y:p.y+tileH/2},{x:p.x-tileW/2,y:p.y}];poly(top,road?'#263c32':((x+y)%2?'#163126':'#19372a'),road?'#466253':'#28503e');if(y===6){poly([top[2],top[3],{x:top[3].x,y:top[3].y+10},{x:top[2].x,y:top[2].y+10}],'#0b1c17')}if(build){ctx.strokeStyle=state.hover&&state.hover.x===x&&state.hover.y===y?'#c9ff7b':'rgba(96,218,145,.36)';ctx.lineWidth=1.5;ctx.beginPath();ctx.ellipse(p.x,p.y,19,9,0,0,Math.PI*2);ctx.stroke();ctx.fillStyle='rgba(97,221,146,.05)';ctx.fill()}}
  function tower(t){const p=iso(t.x,t.y);ctx.fillStyle='rgba(0,0,0,.35)';ctx.beginPath();ctx.ellipse(p.x,p.y+9,22,9,0,0,Math.PI*2);ctx.fill();poly([{x:p.x,y:p.y-2},{x:p.x+18,y:p.y+7},{x:p.x,y:p.y+16},{x:p.x-18,y:p.y+7}],'#304d42');poly([{x:p.x-18,y:p.y+7},{x:p.x,y:p.y+16},{x:p.x,y:p.y+25},{x:p.x-18,y:p.y+16}],'#152921');poly([{x:p.x+18,y:p.y+7},{x:p.x,y:p.y+16},{x:p.x,y:p.y+25},{x:p.x+18,y:p.y+16}],'#20372e');ctx.save();ctx.translate(p.x,p.y-4);ctx.rotate(t.angle||-.3);ctx.fillStyle=types[t.type].color;ctx.fillRect(0,-3,t.type==='rapid'?25:30,t.type==='rapid'?3:7);if(t.type==='rapid')ctx.fillRect(0,3,23,3);ctx.restore();ctx.fillStyle=t.type==='cannon'?'#647c72':t.type==='rapid'?'#357f70':'#819c50';ctx.beginPath();ctx.arc(p.x,p.y-3,11,0,Math.PI*2);ctx.fill();ctx.fillStyle='#a5c7b7';ctx.beginPath();ctx.arc(p.x-3,p.y-6,3,0,Math.PI*2);ctx.fill()}
  function enemy(e){const p=pathPoint(e.progress);e.sx=p.x;e.sy=p.y;ctx.fillStyle='rgba(0,0,0,.4)';ctx.beginPath();ctx.ellipse(p.x,p.y+9,e.boss?19:10,e.boss?8:4,0,0,Math.PI*2);ctx.fill();const r=e.boss?17:9;ctx.fillStyle=e.flash?'#fff':e.boss?'#b64237':'#d85a4f';ctx.beginPath();ctx.moveTo(p.x,p.y-r);ctx.lineTo(p.x+r,p.y);ctx.lineTo(p.x,p.y+r*.7);ctx.lineTo(p.x-r,p.y);ctx.closePath();ctx.fill();ctx.fillStyle='#ffbd70';ctx.fillRect(p.x-4,p.y-2,8,3);const bw=e.boss?40:20;ctx.fillStyle='#251512';ctx.fillRect(p.x-bw/2,p.y-r-7,bw,3);ctx.fillStyle='#ef675d';ctx.fillRect(p.x-bw/2,p.y-r-7,bw*Math.max(0,e.hp/e.maxHp),3);e.flash=false}
  function pathPoint(v){const max=path.length-1,idx=Math.min(Math.floor(v),max-1),f=v-idx,a=iso(path[idx].x,path[idx].y),b=iso(path[idx+1].x,path[idx+1].y);return{x:a.x+(b.x-a.x)*f,y:a.y+(b.y-a.y)*f-7}}
  function drawShot(s){ctx.strokeStyle=s.color;ctx.lineWidth=s.chain?2:1.5;ctx.globalAlpha=Math.max(0,s.life/.15);ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(s.tx,s.ty);ctx.stroke();ctx.globalAlpha=1}
  function drawParticle(p){ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size*p.life/p.max,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}
  function draw(){ctx.clearRect(0,0,W,H);ctx.strokeStyle='rgba(82,138,108,.08)';ctx.lineWidth=1;for(let x=-W;x<W*2;x+=44){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x+H*2,H);ctx.stroke()}for(let x=-W;x<W*2;x+=44){ctx.beginPath();ctx.moveTo(x,H);ctx.lineTo(x+H*2,0);ctx.stroke()}for(let y=0;y<7;y++)for(let x=0;x<10;x++){const road=path.some(q=>q.x===x&&q.y===y),build=buildable.some(q=>q.x===x&&q.y===y)&&!state.towers.some(t=>t.x===x&&t.y===y);tile(x,y,road,build)}state.towers.slice().sort((a,b)=>a.x+a.y-b.x-b.y).forEach(tower);state.enemies.slice().sort((a,b)=>a.progress-b.progress).forEach(enemy);state.shots.forEach(drawShot);state.particles.forEach(drawParticle)}
  function statsFor(t){const base=types[t.type];return{rate:base.rate*(state.skills.has('tempo')?.75:1),damage:base.damage*(state.skills.has('power')?1.3:1),range:base.range}}
  function update(dt){if(state.paused)return;state.time+=dt;if(state.active){state.spawnTimer-=dt;if(state.spawnLeft>0&&state.spawnTimer<=0){spawnEnemy(state.wave===10&&state.spawnLeft===1);state.spawnLeft--;state.spawnTimer=Math.max(.32,.78-state.wave*.035)}if(state.spawnLeft===0&&state.enemies.length===0)finishWave()}
    state.enemies.forEach(e=>{e.progress+=dt*(e.boss?.18:(.31+state.wave*.009));if(e.progress>=path.length-1){e.dead=true;state.hp-=e.boss?5:1;toast('CORE IMPACT  −'+(e.boss?5:1));updateUI();if(state.hp<=0)gameOver()}});state.enemies=state.enemies.filter(e=>!e.dead);
    state.towers.forEach(t=>{t.cool-=dt;let target=state.enemies.filter(e=>{const p=iso(t.x,t.y);return Math.hypot(e.sx-p.x,e.sy-p.y)<statsFor(t).range}).sort((a,b)=>b.progress-a.progress)[0];if(target){const p=iso(t.x,t.y);t.angle=Math.atan2(target.sy-p.y,target.sx-p.x);if(t.cool<=0){fire(t,target);t.cool=statsFor(t).rate}}});state.shots.forEach(s=>s.life-=dt);state.shots=state.shots.filter(s=>s.life>0);state.particles.forEach(p=>{p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt});state.particles=state.particles.filter(p=>p.life>0)}
  function fire(t,e){const p=iso(t.x,t.y),st=statsFor(t);state.shots.push({x:p.x,y:p.y-5,tx:e.sx,ty:e.sy,color:types[t.type].color,life:.13});hit(e,st.damage,t.type==='cannon');t.hits=(t.hits||0)+1;if(state.skills.has('chain')&&t.hits%8===0){const nearby=state.enemies.filter(n=>n!==e&&!n.dead).slice(0,3);let from=e;nearby.forEach(n=>{state.shots.push({x:from.sx,y:from.sy,tx:n.sx,ty:n.sy,color:'#d8fb72',life:.18,chain:true});hit(n,st.damage*.65,false);from=n})}}
  function hit(e,dmg,splash){e.hp-=dmg;e.flash=true;burst(e.sx,e.sy,splash?'#ffb35e':'#79dfff',splash?8:3);if(splash)state.enemies.forEach(n=>{if(n!==e&&Math.hypot(n.sx-e.sx,n.sy-e.sy)<48)n.hp-=dmg*.35});if(e.hp<=0&&!e.dead)kill(e)}
  function kill(e){e.dead=true;state.kills++;state.credits+=e.boss?120:9+Math.floor(state.wave/3);gainXp(e.boss?80:14);burst(e.sx,e.sy,'#ff655b',state.skills.has('blast')?22:10);if(state.skills.has('blast'))state.enemies.forEach(n=>{if(!n.dead&&Math.hypot(n.sx-e.sx,n.sy-e.sy)<75){n.hp-=25;if(n.hp<=0)kill(n)}});updateUI()}
  function burst(x,y,color,count){for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,sp=20+Math.random()*55;state.particles.push({x,y,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp,life:.25+Math.random()*.35,max:.6,size:2+Math.random()*4,color})}}
  function spawnEnemy(boss=false){const hp=(boss?420:48+state.wave*18)*(1+state.wave*.04);state.enemies.push({progress:0,hp,maxHp:hp,boss,dead:false,sx:0,sy:0})}
  function startWave(){if(state.active||state.wave>=10)return;state.wave++;state.active=true;state.spawnLeft=state.wave===10?10:6+state.wave*2;state.spawnTimer=.2;$('waveButton').disabled=true;$('waveBanner').querySelector('strong').textContent='WAVE '+state.wave;$('waveBanner').querySelector('span').textContent=state.wave===10?'WARDEN UNIT DETECTED':'SCOUT FORMATION';$('waveBanner').classList.add('show');setTimeout(()=>$('waveBanner').classList.remove('show'),1600);if(state.wave===10)$('bossBar').classList.remove('hidden');updateUI()}
  function finishWave(){state.active=false;state.credits+=25+state.wave*4;state.energy=Math.min(5,state.energy+1);$('waveButton').disabled=false;if(state.wave===3){document.querySelector('[data-type="support"]').classList.remove('locked');toast('SUPPORT UNIT UNLOCKED')}else toast('WAVE CLEAR  +'+(25+state.wave*4)+' ◇');if(state.wave===10){toast('SECTOR SECURED — RUN COMPLETE');$('waveButton').disabled=true}$('bossBar').classList.add('hidden');updateUI()}
  function gainXp(v){state.xp+=v;const need=100+(state.level-1)*60;if(state.xp>=need){state.xp-=need;state.level++;state.points++;toast('SKILL POINT ACQUIRED')}updateUI()}
  function updateUI(){$('credits').textContent=state.credits;$('coreHp').textContent=Math.max(0,state.hp);$('energy').textContent=state.energy;$('kills').textContent=String(state.kills).padStart(3,'0');$('waveCount').innerHTML=String(Math.max(1,state.wave)).padStart(2,'0')+' <small>/ 10</small>';$('progressText').textContent=state.wave+' / 10';$('progressFill').style.width=state.wave*10+'%';$('runLevel').textContent=state.level;const need=100+(state.level-1)*60;$('xpText').textContent=state.xp+' / '+need+' XP';$('xpFill').style.width=state.xp/need*100+'%';$('skillPoints').textContent=state.points;$('modalPoints').textContent=state.points;$('rating').textContent=state.wave>8?'S':state.wave>6?'A':state.wave>4?'B':state.wave>2?'C':'D';$('enemyTotal').textContent=state.wave===9?'1':8+state.wave*2;$('enemyName').textContent=state.wave===9?'WARDEN UNIT':state.wave>5?'ARMORED SWARM':'FERAL DRONES'}
  function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1800)}
  function gameOver(){state.active=false;state.paused=true;$('waveButton').disabled=true;toast('CORE LOST — REFRESH TO RETRY')}
  function loop(now){const dt=Math.min(.04,(now-last)/1000)*state.speed;last=now;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
  function mouseTile(ev){const r=canvas.getBoundingClientRect(),mx=ev.clientX-r.left,my=ev.clientY-r.top;let best=null,dist=1e9;buildable.forEach(q=>{const p=iso(q.x,q.y),d=Math.hypot(mx-p.x,my-p.y);if(d<dist){dist=d;best=q}});return dist<30?best:null}
  canvas.addEventListener('mousemove',e=>{state.hover=mouseTile(e)});canvas.addEventListener('mouseleave',()=>state.hover=null);canvas.addEventListener('click',e=>{const q=mouseTile(e);if(!q)return;if(state.towers.some(t=>t.x===q.x&&t.y===q.y)){toast('NODE OCCUPIED');return}const cfg=types[state.selected];if(state.credits<cfg.cost){toast('INSUFFICIENT CREDITS');return}state.credits-=cfg.cost;state.towers.push({...q,type:state.selected,cool:.2,angle:-.3});burst(iso(q.x,q.y).x,iso(q.x,q.y).y,'#75eda1',12);updateUI()});
  document.querySelectorAll('.tower-card').forEach(b=>b.addEventListener('click',()=>{if(b.classList.contains('locked'))return;document.querySelectorAll('.tower-card').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.selected=b.dataset.type}));
  $('waveButton').onclick=startWave;document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>{state.speed=+b.dataset.speed;state.paused=false;document.querySelectorAll('.speed-controls button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});$('pauseButton').onclick=()=>{state.paused=!state.paused;$('pauseButton').classList.toggle('active',state.paused)};
  function modal(id,on){$(id).classList.toggle('open',on);$(id).setAttribute('aria-hidden',String(!on))}$('treeButton').onclick=()=>modal('skillModal',true);$('closeSkills').onclick=$('closeSkillsBottom').onclick=()=>modal('skillModal',false);document.querySelector('.modal-backdrop').onclick=()=>modal('skillModal',false);$('helpButton').onclick=()=>modal('helpModal',true);$('closeHelp').onclick=()=>modal('helpModal',false);$('helpModal').onclick=e=>{if(e.target===$('helpModal'))modal('helpModal',false)};
  document.querySelectorAll('.skill-node').forEach(n=>n.addEventListener('click',()=>{if(!n.classList.contains('available')||state.points<1)return;state.points--;state.skills.add(n.dataset.skill);n.classList.remove('available');n.classList.add('owned');if(n.dataset.skill==='power')document.querySelector('.n3').classList.add('available');if(n.dataset.skill==='tempo')document.querySelector('.n4').classList.add('available');if(state.skills.has('blast')&&state.skills.has('chain'))document.querySelector('.apex').classList.add('available');toast(n.querySelector('strong').textContent+' ACTIVATED');updateUI()}));
  $('soundButton').onclick=()=>{$('soundButton').textContent=$('soundButton').textContent==='◖'?'×':'◖';toast('AUDIO '+($('soundButton').textContent==='×'?'MUTED':'ONLINE'))};$('settingsButton').onclick=()=>toast('SYSTEMS NOMINAL');updateUI();
})();
